modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="netherstararsenal"
version="1.0.0"
displayName="Nether Star Arsenal"
description='''
A progression mod that adds balanced Nether Star-based armor and tools to Minecraft.
Features Nether Star armor with moderate protection and useful bonuses, tools with enhanced efficiency,
and a foundation for deep progression gameplay. Perfect for modpacks focused on balanced progression.
''' 